DROP DATABASE IF EXISTS hospital_db;
CREATE DATABASE hospital_db;
USE hospital_db;

CREATE TABLE organizations (
    Id CHAR(36) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE CHAR(2),
    ZIP VARCHAR(10),
    LAT DECIMAL(10, 6),
    LON DECIMAL(10, 6)
);

CREATE TABLE payers (
    Id CHAR(36) PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE_HEADQUARTERED CHAR(2),
    ZIP VARCHAR(10),
    PHONE VARCHAR(20)
);

CREATE TABLE patients (
    Id CHAR(36) PRIMARY KEY,
    BIRTHDATE DATE,
    DEATHDATE DATE,
    PREFIX VARCHAR(10),
    FIRST VARCHAR(100),
    LAST VARCHAR(100),
    SUFFIX VARCHAR(10),
    MAIDEN VARCHAR(100),
    MARITAL CHAR(1),
    RACE VARCHAR(50),
    ETHNICITY VARCHAR(50),
    GENDER CHAR(1),
    BIRTHPLACE VARCHAR(255),
    ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(100),
    COUNTY VARCHAR(100),
    ZIP VARCHAR(10),
    LAT DECIMAL(12, 8),
    LON DECIMAL(12, 8)
);

CREATE TABLE encounters (
    Id CHAR(36) PRIMARY KEY,
    START DATETIME,
    STOP DATETIME,
    PATIENT CHAR(36),
    ORGANIZATION CHAR(36),
    PAYER CHAR(36),
    ENCOUNTERCLASS VARCHAR(50),
    CODE VARCHAR(30),
    DESCRIPTION VARCHAR(255),
    BASE_ENCOUNTER_COST DECIMAL(12, 2),
    TOTAL_CLAIM_COST DECIMAL(12, 2),
    PAYER_COVERAGE DECIMAL(12, 2),
    REASONCODE VARCHAR(30),
    REASONDESCRIPTION VARCHAR(255),
    CONSTRAINT fk_encounters_patient FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    CONSTRAINT fk_encounters_organization FOREIGN KEY (ORGANIZATION) REFERENCES organizations(Id),
    CONSTRAINT fk_encounters_payer FOREIGN KEY (PAYER) REFERENCES payers(Id)
);

CREATE TABLE procedures (
    Id BIGINT AUTO_INCREMENT PRIMARY KEY,
    START DATETIME,
    STOP DATETIME,
    PATIENT CHAR(36),
    ENCOUNTER CHAR(36),
    CODE VARCHAR(30),
    DESCRIPTION VARCHAR(255),
    BASE_COST DECIMAL(12, 2),
    REASONCODE VARCHAR(30),
    REASONDESCRIPTION VARCHAR(255),
    CONSTRAINT fk_procedures_patient FOREIGN KEY (PATIENT) REFERENCES patients(Id),
    CONSTRAINT fk_procedures_encounter FOREIGN KEY (ENCOUNTER) REFERENCES encounters(Id)
);

CREATE INDEX idx_encounters_start ON encounters(START);
CREATE INDEX idx_encounters_patient_start ON encounters(PATIENT, START);
CREATE INDEX idx_encounters_class ON encounters(ENCOUNTERCLASS);
CREATE INDEX idx_encounters_payer ON encounters(PAYER);
CREATE INDEX idx_procedures_code ON procedures(CODE);
CREATE INDEX idx_procedures_encounter ON procedures(ENCOUNTER);
